### ISSUE TITLE
Improve Performance by indexing short codes

### ISSUE THREAD

**Issue by Kamyab7** [mohammadKarimi/SwiftLink#5]
Hey @mohammadKarimi 

We can increase read operation from the database by indexing shortcodes, I will create a PR to tackle this issue.

**Comment by mohammadKarimi** [comment]
Yes, in this area of Project, I wouldn't spend time to performance. because I think this type of performance can be delayed. 
but if you want to work on it, feel free.

**Comment by Kamyab7** [comment]
Happy to hear that :)
