### ISSUE TITLE
Update a swiftlink

### ISSUE THREAD

**Issue by mohammadKarimi** [mohammadKarimi/SwiftLink#69]
Updates fields in the specified link.

**Comment by parhamdarvishi** [comment]
mohammad I want to add this option to system.

**Comment by mohammadKarimi** [comment]
It is yours now 😉

**Comment by parhamdarvishi** [comment]
its an honor.

I create a PR -> "UpdateLinkAPI"

so I have some question around this issue:
witch fields must be in update:
now I only added title.

another question is about the result of API:
what is the best practice for API result? is it good to only return bool ?(I used this type)
or we must create custom output DTO?

**Comment by mohammadKarimi** [comment]
> its an honor.
> 
> I create a PR -> "UpdateLinkAPI"
> 
> so I have some question around this issue:
> witch fields must be in update:
> now I only added title.
> 
> another question is about the result of API:
> what is the best practice for API result? is it good to only return bool ?(I used this type)
> or we must create custom output DTO?

I sent you which fields must be updated, now you can see them on your PR.
