### ISSUE TITLE
Disable a swiftlink

### ISSUE THREAD

**Issue by mohammadKarimi** [mohammadKarimi/SwiftLink#70]

**Comment by parhamdarvishi** [comment]
I added disable property for link entity in domain

**Comment by mohammadKarimi** [comment]
Okay, thank you. Consider the need for a delete method (HTTP method) to disable a link and set this field to true for disabling. Additionally, in the update mechanism, we can set this field to true again.

**Comment by mohammadKarimi** [comment]
@parhamdarvishi I asssign this issue to you. make a branch for this issue then send me PR.
