### ISSUE TITLE
Database connection string 

### ISSUE THREAD

**Issue by Kamyab7** [mohammadKarimi/SwiftLink#85]
I am not sure but I think SSMS provides a server instance which name is (localdb)\\mssqllocaldb as default which means we can replace this personal connection string `Server=DESKTOP-TVCSFN3\\MHA;Database=SwiftLink;Trusted_Connection=True;Encrypt=false` by `Server=(localdb)\\mssqllocaldb;Database=SwiftLink;Trusted_Connection=True;MultipleActiveResultSets=true` by doing so we can remove `Updating Database and Connection String` part from readme file cause it will already correct for all the machines.

**Comment by mohammadKarimi** [comment]
We should improve us step by step, I will check your comment. After seed initializer we can remove this section from readme file to make it better.

**Comment by mohammadKarimi** [comment]
For connection string we can use UserSecret file in development phase, in this case, every one can set own ConnectionString.

**Comment by mohammadKarimi** [comment]
After all, we will reduce the parts of readme file to reduce the preparing time.

For inctance, in development mode, we can use, pending migration method in ef core to detect database is sync or not, and sync database for users automatically.

**Comment by mohammadKarimi** [comment]
For connection string, please use UserSecret File, and add it with Visual Studio.
